### ISSUE TITLE
New release is needed to make @latest not break

### ISSUE THREAD

**Issue by morphar** [google/gnostic#285] opened 2022-01-08 07:23 UTC
@timburks just in case, you missed the comment in #283 ;)
It seems we need and actual release to make this work again:
`github.com/google/gnostic/cmd/protoc-gen-openapi@latest`
It ignores the tag and uses the release.
This works:
`github.com/google/gnostic/cmd/protoc-gen-openapi@v0.6.1`

**Comment by timburks** [comment] 2022-01-08 07:29
Hi, please try now - I just created a release for v0.6.1

**Comment by morphar** [comment] 2022-01-08 07:37
Thanks 👍 
Unfortunately it still doesn't work, at least for me.
I may have misinterpreted the issue - when I do:
`go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest`
It still tries to fetch:
`github.com/google/gnostic/cmd/protoc-gen-openapi@v0.0.0-20220107061744-94bcf11351a5`
Which is the commit used in v0.6.0.

So I think it will eventually work, when something in the entire chain of go module proxying loses it's cache.
I will try to force it, by opening the repo on go.dev.

**Comment by morphar** [comment] 2022-01-08 07:38
Nopes.... May be some caching on my computer then

**Comment by timburks** [comment] 2022-01-08 07:40
Does it help to run `go clean -modcache` locally?

**Comment by morphar** [comment] 2022-01-08 07:43
Will try 👍

**Comment by morphar** [comment] 2022-01-08 07:48
Still no... Weird

**Comment by morphar** [comment] 2022-01-08 07:48
It actually seems to download v0.6.1 and the code looks right

**Comment by shenqidebaozi** [comment] 2022-01-08 07:49
@timburks @morphar It may be because we added a separate `go.mod` file before, and there may be some cache problems. What he obtained is the code of the previous separate `go.mod` Is there a way to force the refresh of `pkg.go.dev`. What about cache?

**Comment by morphar** [comment] 2022-01-08 07:49
So it downloads the v0.6.1 code, but the v0.6.0 code for the protoc-gen-openapi command.

**Comment by morphar** [comment] 2022-01-08 07:50
@shenqidebaozi I have cleaned out my local cache, so it must be upstream or a "misunderstanding" of which version of protoc-gen-openapi to fetch

**Comment by shenqidebaozi** [comment] 2022-01-08 07:51
@morphar Yes, because a separate module file has been added before, it may have an upstream cache. Is there any way to clear the upstream cache?

**Comment by morphar** [comment] 2022-01-08 07:52
No idea.
If I remove everything in mo ~/go dir and run this: `go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest`
Then I get this:
```
go: downloading github.com/google/gnostic/cmd/protoc-gen-openapi v0.0.0-20220107061744-94bcf11351a5
go: downloading github.com/google/gnostic v0.6.1
go install: github.com/google/gnostic/cmd/protoc-gen-openapi@latest (in github.com/google/gnostic/cmd/protoc-gen-openapi@v0.0.0-20220107061744-94bcf11351a5):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Comment by shenqidebaozi** [comment] 2022-01-08 07:53
@morphar https://pkg.go.dev/github.com/google/gnostic/cmd/protoc-gen-openapi

**Comment by morphar** [comment] 2022-01-08 07:54
I see what you mean: somewhere, it knows about the go.mod for https://pkg.go.dev/github.com/google/gnostic/cmd/protoc-gen-openapi, but not that is has been removed.

**Comment by morphar** [comment] 2022-01-08 07:54
It may be necessary to remove v0.6.0 release entirely to make this work again:
`go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest`

**Comment by shenqidebaozi** [comment] 2022-01-08 07:55
@morphar https://pkg.go.dev/about#best-practices-h2 There is a way to delete it

**Comment by morphar** [comment] 2022-01-08 07:56
Nice! Thanks for finding that @shenqidebaozi ! :)

**Comment by shenqidebaozi** [comment] 2022-01-08 07:57
@morphar You're welcome. After all, I started the problem

**Comment by morphar** [comment] 2022-01-08 07:57
Just for context:

```
Removing a package
If you would like to hide versions of a module on pkg.go.dev, as well as from the go command, you should retract them. Retracting a module version involves adding a retract directive to your go.mod file and publishing a new version. See the Go blog post [New module changes](https://go.dev/blog/go116-module-changes#TOC_5.) in Go 1.16 and the [modules reference](https://go.dev/ref/mod#go-mod-file-retract) for details.
```

**Comment by morphar** [comment] 2022-01-08 07:58
@shenqidebaozi we all looked at the code and agreed that it looked right ;)

**Comment by shenqidebaozi** [comment] 2022-01-08 07:59
You can also consider submitting the deletion request directly

>If you cannot retract your module, you can file a request for the pkgsite team to remove your package.

**Comment by morphar** [comment] 2022-01-08 08:03
Should be retracted with #286

**Comment by morphar** [comment] 2022-01-08 08:38
Temporare solution:
`go install github.com/google/gnostic/cmd/protoc-gen-openapi@v0.6.1`

**Comment by timburks** [comment] 2022-01-08 18:34
Thanks for analyzing this! I think adding the retraction should be sufficient based on the following:
```
If you cannot retract your module, you can file a request for the pkgsite team to remove your package.
```
But let's see - if we still have problems after the merge, we can submit that request.

**Comment by timburks** [comment] 2022-01-08 18:44
So, it seems that there's still a problem; I guess this is related to the deleted `go.mod` files.
```
$ go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest
go: downloading github.com/google/gnostic v0.6.2
go: downloading github.com/google/gnostic/cmd/protoc-gen-openapi v0.0.0-20220107061744-94bcf11351a5
go: github.com/google/gnostic/cmd/protoc-gen-openapi@latest (in github.com/google/gnostic/cmd/protoc-gen-openapi@v0.0.0-20220107061744-94bcf11351a5):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Comment by timburks** [comment] 2022-01-08 18:58
https://github.com/golang/go/issues/50514

**Comment by morphar** [comment] 2022-01-08 19:02
Nice! Thanks @timburks 👍

**Comment by morphar** [comment] 2022-01-09 21:37
@timburks I have been trying to figure out, how to actually retract the multi-module from the modcache.
I started with a failed attempt, using @seankhliao's advice, which seems to be caused by `v0.0.0-00000000000000-000000000000` in the retract command:
```
retract [v0.0.0-00000000000000-000000000000, v0.6.1]
```

If I change the `v0.0.0-00000000000000-000000000000` to what I get, when calling:
`go clean -modcache && go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest`
then it actually seems to work.

I recreated our scenario in [morphar/testgomod](https://github.com/morphar/testgomod) and this is the procedure that seems to work:

1. call go install for each cmd with @latest tag and note the version downloaded (e.g. v0.0.0-20220107061744-94bcf11351a5)
2. create a go.mod for each cmd, with a retract containing the noted version + the planned release (higher than the latest root tag e.g. v0.6.3)
ex: `retract [v0.0.0-20220107061744-94bcf11351a5, v0.6.3]`
3. create a new multi-module tag for each cmd, e.g. `cmd/protoc-gen-openapi/v0.6.3`
4. remove all go.mod files from cmds
5. create a new tag, higher than the tag used for the multi-module tags, e.g. `v0.6.4`

This seems to fix the use of go install @latest for all cmds and the pkg.go.dev documentation for the latest version (v.0.6.4).

I'm not 100% confident in this procedure, as I ended up in a weird state with my first attempt. But the last attempt seems to have ended in a correct state.

# Notes
I used these commands a lot during testing, to trigger updates and fetch new versions:
```bash
go clean -modcache && go install github.com/morphar/testgomod@latest
go clean -modcache && go install github.com/morphar/testgomod@v0.1.1
go clean -modcache && go install github.com/morphar/testgomod/cmd/submod@latest
go clean -modcache && go install github.com/morphar/testgomod/cmd/submod@v0.1.1
curl https://proxy.golang.org/github.com/morphar/testgomod/@v/v0.1.1.info
curl https://proxy.golang.org/github.com/morphar/testgomod/cmd/submod/@v/v0.1.1.info
```

**Comment by morphar** [comment] 2022-01-10 09:13
It actually seems like it's only `protoc-gen-openapi` that have issues.
```
go: downloading github.com/google/gnostic/cmd/protoc-gen-openapi v0.0.0-20220107061744-94bcf11351a5
go install: github.com/google/gnostic/cmd/protoc-gen-openapi@latest (in github.com/google/gnostic/cmd/protoc-gen-openapi@v0.0.0-20220107061744-94bcf11351a5):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Comment by morphar** [comment] 2022-01-10 12:17
#288 + #289 should fix the issues

**Comment by timburks** [comment] 2022-01-22 17:41
@morphar I've merged #288, pushed the v0.6.3 tags, merged #289, pushed a v0.6.4 tag, and created a release for v0.6.4.

Let's verify this now. My first attempt was unsuccessful, but maybe something needs to propagate or a cache needs clearing:
```
$ go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest
go: downloading github.com/google/gnostic v0.6.3
go: github.com/google/gnostic/cmd/protoc-gen-openapi@latest: module github.com/google/gnostic@latest found (v0.6.3), but does not contain package github.com/google/gnostic/cmd/protoc-gen-openapi
```

**Comment by morphar** [comment] 2022-01-22 17:42
@timburks I'll give it a try 👍

**Comment by timburks** [comment] 2022-01-22 17:43
Another reference, after clearing my cache and modcache:
```
$ go install github.com/google/gnostic/cmd/protoc-gen-openapi@v0.6.4
go: downloading github.com/google/gnostic v0.6.4
go: github.com/google/gnostic/cmd/protoc-gen-openapi@v0.6.4: module github.com/google/gnostic@v0.6.4 found, but does not contain package github.com/google/gnostic/cmd/protoc-gen-openapi
```

**Comment by morphar** [comment] 2022-01-22 17:44
Same for me:
```
$ go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest
go: downloading github.com/google/gnostic v0.6.4
go install: github.com/google/gnostic/cmd/protoc-gen-openapi@latest: module github.com/google/gnostic@latest found (v0.6.4), but does not contain package github.com/google/gnostic/cmd/protoc-gen-openapi
```

**Comment by morphar** [comment] 2022-01-22 17:45
I hope that it has to do with cache...

**Comment by timburks** [comment] 2022-01-22 17:48
`go install -v github.com/google/gnostic/cmd/protoc-gen-openapi@v0.6.3` works for me. Catching up on the discussion of the [removal request](https://github.com/golang/go/issues/50514), I wonder if we might need to keep the reverting go.mods in the `cmd` subdirectories.

**Comment by morphar** [comment] 2022-01-22 17:49
This is weird, it's the exact same procedure as I did with [morphar/testgomod](https://github.com/morphar/testgomod).
It works for v0.1.3, which corresponds to v0.6.4 in gnostic.

**Comment by morphar** [comment] 2022-01-22 17:51
In testgomod I also removed the breaking go.mod and any revert commands.

**Comment by timburks** [comment] 2022-01-22 17:54
Going back through the tags:

- `go install -v github.com/google/gnostic/cmd/protoc-gen-openapi@v0.6.4` fails
- `go install -v github.com/google/gnostic/cmd/protoc-gen-openapi@v0.6.3` works
- `go install -v github.com/google/gnostic/cmd/protoc-gen-openapi@v0.6.2` works
- `go install -v github.com/google/gnostic/cmd/protoc-gen-openapi@v0.6.1` works
- `go install -v github.com/google/gnostic/cmd/protoc-gen-openapi@v0.6.0` fails

**Comment by morphar** [comment] 2022-01-22 17:54
E.g.:
```
$ go install github.com/morphar/testgomod/cmd/submod@latest 
go: downloading github.com/morphar/testgomod v0.1.3
```

**Comment by morphar** [comment] 2022-01-22 17:55
@timburks I really do not get, why v0.6.4 fails...
But as you suggested, maybe it will work if we keep the revert command.
At this point it's back to just guessing.

**Comment by timburks** [comment] 2022-01-22 17:58
@morphar are you able to reproduce any failures in your test repo? Running `go install` on the tags that I see there, I find that all of them succeed.
- `go install github.com/morphar/testgomod/cmd/submod@latest`
- `go install github.com/morphar/testgomod/cmd/submod@v0.1.3`
- `go install github.com/morphar/testgomod/cmd/submod@v0.1.2`
- `go install github.com/morphar/testgomod/cmd/submod@v0.1.1`
- `go install github.com/morphar/testgomod/cmd/submod@v0.1.0`

**Comment by morphar** [comment] 2022-01-22 17:58
@timburks another thing that wonder me, is that this works:
https://pkg.go.dev/github.com/morphar/testgomod/cmd/submod@v0.1.3
While this doesn't:
https://pkg.go.dev/github.com/google/gnostic/cmd/protoc-gen-openapi@v0.6.4

Again: it's the exact same procedure

**Comment by timburks** [comment] 2022-01-22 18:00
So I'm thinking we should try rebasing on v0.6.3, tagging it as v0.6.5, and pushing that

**Comment by morphar** [comment] 2022-01-22 18:02
No I don't get any errors with the test repo either... I really don't know what to think anymore.
I followed the steps we made 1 by 1, ensuring I got the same errors and then tried to fix it with the revert commands.
So I don' understand why there's no errors in my test repo, but there is in gnostic.

**Comment by morphar** [comment] 2022-01-22 18:03
Sure 👍 If that fixes the issue, I'm all for it.

**Comment by morphar** [comment] 2022-01-22 18:05
I think I know what happened!

**Comment by morphar** [comment] 2022-01-22 18:06
The last pull request "broke" when it was merged with the last merge - some files should have been removed, but there is 0 changes it seems.
Let me just have a better look and make sure I'm right.

**Comment by timburks** [comment] 2022-01-22 18:08
@morphar yes, I just found that all the `cmd/*/go.mod` files are still present

**Comment by morphar** [comment] 2022-01-22 18:08
Yep.
The last pull request was supposed to remove all go.mod files from the sub modules, but that got lost somehow:
This was my original commit:
<img width="759" alt="Screenshot 2022-01-22 at 19 08 04" src="https://user-images.githubusercontent.com/189420/150650354-70dabd41-8313-4d88-86aa-8a2cd4488615.png">

**Comment by morphar** [comment] 2022-01-22 18:10
Yes, I can see that merging master into the pull request restored the files.
Do you want me to update the pull request?

**Comment by timburks** [comment] 2022-01-22 18:11
I don't see how this explains what we're seeing - installing `v0.6.4` fails and `v0.6.3` succeeds. Do you understand why that's happening?

**Comment by morphar** [comment] 2022-01-22 18:13
Maybe it's due to the fact, that the retract says: `retract [v0.0.0-20220107061744-94bcf11351a5, v0.6.3]`
So v0.6.4 returns to using the go.mod?

**Comment by timburks** [comment] 2022-01-22 18:14
OK, that makes sense. Do we need two more commits to fix this? (updating the retract version and removing the files)?

**Comment by morphar** [comment] 2022-01-22 18:15
I think we do :)
Maybe something like:
- create 1 pull request
- update the repo
- pull those changes
- delete the go.mod files
- create new pull request

Just to make sure the same doesn't happen :)

**Comment by timburks** [comment] 2022-01-22 18:17
OK, I can do those now, or if you have time, I'll approve and merge them.

**Comment by timburks** [comment] 2022-01-22 18:18
Let's make the second PR after the first is merged to avoid needing to update the PR to merge.

**Comment by morphar** [comment] 2022-01-22 18:18
I'm good with both. I do have the time :)

**Comment by morphar** [comment] 2022-01-22 18:22
I think we need to add something like this to the root go.mod:
`retract [v0.6.0, v0.6.4]`

**Comment by timburks** [comment] 2022-01-22 18:24
Also, let's pause and test installing `@latest` of `@v0.6.5` when we have that

**Comment by timburks** [comment] 2022-01-22 18:38
Got the first PR. Why did we need the `cmd` tags for `v0.6.3`? Do we need them again?

**Comment by timburks** [comment] 2022-01-22 18:41
`v0.6.5` is pushed.

**Comment by morphar** [comment] 2022-01-22 18:42
Aaaahhh.... Good point! I probably should have used commit hash... Damn it!

**Comment by seankhliao** [comment] 2022-01-22 18:42
Yes you need the `cmd/*/v0.6.5` tags, they're needed to publish the `cmd/*` modules so they can retract themselves

**Comment by morphar** [comment] 2022-01-22 18:43
Thanks @seankhliao 👍 So we need to re-introduce all of the `cmd/*/v0.6.5` tags and then we can push a version with only 1 go.mod file and a v0.6.6 tag.

**Comment by seankhliao** [comment] 2022-01-22 18:44
yes, that's right

**Comment by timburks** [comment] 2022-01-22 18:44
Makes sense. I see that just adding the top-level tag isn't enough to successfully install the `cmd` components

**Comment by morphar** [comment] 2022-01-22 18:45
`cmd/*/v0.6.5` should do the trick 👍

**Comment by morphar** [comment] 2022-01-22 18:46
I wonder if this sort of thing will be easier i Go v1.8... :)

**Comment by timburks** [comment] 2022-01-22 18:50
I tagged and pushed `cmd/disco/v0.6.5`. `go install github.com/google/gnostic/cmd/disco@v0.6.5` is still having problems.
```
$ go install github.com/google/gnostic/cmd/disco@v0.6.5
go: github.com/google/gnostic/cmd/disco@v0.6.5: module github.com/google/gnostic@v0.6.5 found, but does not contain package github.com/google/gnostic/cmd/disco
```

**Comment by morphar** [comment] 2022-01-22 18:51
Same here

**Comment by seankhliao** [comment] 2022-01-22 18:52
that's expected, it won't work until the `cmd/disco/go.mod` file is removed (that's what defines module boundaries)

**Comment by morphar** [comment] 2022-01-22 18:53
I'll remove them in a new pull request then

**Comment by morphar** [comment] 2022-01-22 18:54
We'll probably need v0.6.5 tags for all the commands then

**Comment by timburks** [comment] 2022-01-22 18:55
I pushed all the remaining `cmd/*/v0.6.5` tags.

**Comment by morphar** [comment] 2022-01-22 19:01
Interesting... I get the same - i.e. disco fails, parse-linter-output works.

**Comment by timburks** [comment] 2022-01-22 19:04
I merged #295, pushed v0.6.6, and reran the same set of installs now using `@v0.6.6`, all succeeded.

**Comment by morphar** [comment] 2022-01-22 19:05
Nice!!! It works with @latest too - at least for protoc-gen-openapi.
I'll try the rest as well.

**Comment by timburks** [comment] 2022-01-22 19:05
These also work for me
```
go install github.com/google/gnostic/cmd/disco@latest
go install github.com/google/gnostic/cmd/parse-linter-output@latest
go install github.com/google/gnostic/cmd/petstore-builder@latest
go install github.com/google/gnostic/cmd/protoc-gen-jsonschema@latest
go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest
go install github.com/google/gnostic/cmd/report@latest
go install github.com/google/gnostic/cmd/report-messages@latest
go install github.com/google/gnostic/cmd/vocabulary-operations@latest
```

**Comment by morphar** [comment] 2022-01-22 19:07
I'm probably hitting some cache issues then:
```
$go install github.com/google/gnostic/cmd/disco@latest

go: downloading github.com/google/gnostic/cmd/disco v0.6.5
go install: github.com/google/gnostic/cmd/disco@latest: github.com/google/gnostic/cmd/disco@v0.6.5: verifying module: github.com/google/gnostic/cmd/disco@v0.6.5: reading https://sum.golang.org/lookup/github.com/google/gnostic/cmd/disco@v0.6.5: 410 Gone
	server response: not found: github.com/google/gnostic/cmd/disco@v0.6.5: invalid version: unknown revision cmd/disco/v0.6.5
```

**Comment by morphar** [comment] 2022-01-22 19:08
`go clean -modcache` fixed it! 👍

**Comment by morphar** [comment] 2022-01-22 19:09
Everything works for me as well now! 👍

**Comment by timburks** [comment] 2022-01-22 19:09
I just verified on a second system. I'm using `go1.18beta` on both, fwiw.

**Comment by morphar** [comment] 2022-01-22 19:10
I'm on 1.17.

**Comment by timburks** [comment] 2022-01-22 19:16
Also works on the official `golang:1.16` image. Earlier Go versions don't support the path@version syntax, so I think we've got it fixed. Thanks for researching all of this @morphar and @seankhliao for advising and following!

**Closed by timburks** 2022-01-22 19:16 UTC

**Comment by morphar** [comment] 2022-01-22 19:20
You're very welcome! :) And thanks for ensuring that it went (relatively) smooth with all the pushing, pulling and tagging @timburks :)
Thank you @seankhliao for guiding us! I really appreciate it :)
